package hangyin.dev.stocksimulator.credential;


import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

import java.io.IOException;
import java.security.GeneralSecurityException;

import static org.junit.jupiter.api.Assertions.*;

class CredentialServiceTest {
//    @Autowired CredentialService credentialService;

    @Test
    public void verifyCredentialTest() throws GeneralSecurityException, IOException {
//        credentialService = new CredentialService();
//        credentialService.verifyUserCredential("eyJhbGciOiJSUzI1NiIsImtpZCI6ImU4NzMyZGIwNjI4NzUxNTU1NjIxM2I4MGFjYmNmZDA4Y2ZiMzAyYTkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXpwIjoiNjMyMzMxMjMxNTU3LXV0dnFlOHV0bWRmcWQ3Nzlzajg5MmgwNDM1Nm5tM2o3LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiNjMyMzMxMjMxNTU3LXV0dnFlOHV0bWRmcWQ3Nzlzajg5MmgwNDM1Nm5tM2o3LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTAwNjkxMjYyMzY0Mzk2NDkzMjE1IiwiaGQiOiJjb2x1bWJpYS5lZHUiLCJlbWFpbCI6Imh5MjU2OEBjb2x1bWJpYS5lZHUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6IjV1bXFrbTVjY0VOdGctdjZ6eWlrZUEiLCJuYW1lIjoiSGFuZyBZaW4iLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDUuZ29vZ2xldXNlcmNvbnRlbnQuY29tLy1iX2w4TlFNS2J6NC9BQUFBQUFBQUFBSS9BQUFBQUFBQUFBQS9BTVp1dWNtTllOTXVHQ2ZuOWppWFhlU2lIeDVaakY5cE1nL3M5Ni1jL3Bob3RvLmpwZyIsImdpdmVuX25hbWUiOiJIYW5nIiwiZmFtaWx5X25hbWUiOiJZaW4iLCJsb2NhbGUiOiJlbiIsImlhdCI6MTYxNTM0NDAyMiwiZXhwIjoxNjE1MzQ3NjIyLCJqdGkiOiI0ODUwZTg0NzFiMjc2ODc3ZTc3OWJhODUzYzViMjQ4NmJiY2Y2ZjIxIn0.eYsUvZ9iaW61UmSYzwEq9NPIRzoChM6CPdyeQ2ZTvim823QZMCsqD4E3aWPw-uBj9ACRJpDDX2NqSUk7xGDmK207M0c1fW2vYyYZ1fyBFKfvdv97yMpppAWvqXp5xtZ6CihWKmyhIP4QlBmlI5ale7zlr49wfs9CmSlm3NzMlLflnjhP4rH1hnaEgUBbuegue17IJpOGAFhvnR5Awe3KAr0KaxahvI39zWaKqWU2XY20qx4fZBR4qebKLvrRPs4qvo4asYVoUeHb523LOOyV7_Fn_3x99mK9SmZR_JZXniMwideJzw9itIvQ_geSxAKz4k0n-fWkJpMK6bh4IgkN1g");
//        System.out.println("123");
    }
}